

export type TableFoodType = {
    key: number,
    cat: string,
    kind: string,
    name: string,
    harn: number,
    harnPerPortion: number,
    purin: number,
    purinPerPortion: number,
    portionG: number,
    amount: number
}

export type FoodType = {
    key: number,
    cat: string,
    kind: string,
    name: string,
    harn: number,
    harnPerPortion: number,
    purin: number,
    purinPerPortion: number,
    portionG: number
}

export const data: FoodType[] = [
    {
        "key": 1,
        "cat": "Brot",
        "name": "Knäckebrot",
        "kind": "",
        "harn": 64,
        "harnPerPortion": 6,
        "purin": 27,
        "purinPerPortion": 3,
        "portionG": 10
    },
    {
        "key": 2,
        "cat": "Brot",
        "name": "Leinsamenbrot",
        "kind": "",
        "harn": 52,
        "harnPerPortion": 23,
        "purin": 22,
        "purinPerPortion": 10,
        "portionG": 45
    },
    {
        "key": 3,
        "cat": "Brot",
        "name": "Mischbrot",
        "kind": "",
        "harn": 49,
        "harnPerPortion": 22,
        "purin": 20,
        "purinPerPortion": 9,
        "portionG": 45
    },
    {
        "key": 4,
        "cat": "Brot",
        "name": "Nürnberger Lebkuchen",
        "kind": "",
        "harn": 28,
        "harnPerPortion": 11,
        "purin": 12,
        "purinPerPortion": 5,
        "portionG": 40
    },
    {
        "key": 5,
        "cat": "Brot",
        "name": "Roggenbrot",
        "kind": "",
        "harn": 55,
        "harnPerPortion": 25,
        "purin": 23,
        "purinPerPortion": 10,
        "portionG": 45
    },
    {
        "key": 6,
        "cat": "Brot",
        "name": "Roggenvollkornbrot",
        "kind": "",
        "harn": 57,
        "harnPerPortion": 29,
        "purin": 24,
        "purinPerPortion": 12,
        "portionG": 50
    },
    {
        "key": 7,
        "cat": "Brot",
        "name": "Salzstangen",
        "kind": "",
        "harn": 100,
        "harnPerPortion": 30,
        "purin": 42,
        "purinPerPortion": 13,
        "portionG": 30
    },
    {
        "key": 8,
        "cat": "Brot",
        "name": "Semmel, Brötchen",
        "kind": "",
        "harn": 40,
        "harnPerPortion": 20,
        "purin": 17,
        "purinPerPortion": 8,
        "portionG": 45
    },
    {
        "key": 9,
        "cat": "Brot",
        "name": "Weißbrot",
        "kind": "",
        "harn": 42,
        "harnPerPortion": 13,
        "purin": 18,
        "purinPerPortion": 5,
        "portionG": 30
    },
    {
        "key": 10,
        "cat": "Brot",
        "name": "Weizenvollkornbrot",
        "kind": "",
        "harn": 64,
        "harnPerPortion": 32,
        "purin": 27,
        "purinPerPortion": 13,
        "portionG": 50
    },
    {
        "key": 11,
        "cat": "Brot",
        "name": "Zwieback",
        "kind": "",
        "harn": 60,
        "harnPerPortion": 30,
        "purin": 25,
        "purinPerPortion": 13,
        "portionG": 50
    },
    {
        "key": 12,
        "cat": "Eierspeisen",
        "name": "Eigelb",
        "kind": "",
        "harn": 6,
        "harnPerPortion": 1,
        "purin": 3,
        "purinPerPortion": 0,
        "portionG": 22
    },
    {
        "key": 13,
        "cat": "Eierspeisen",
        "name": "Eiweiß",
        "kind": "",
        "harn": 0,
        "harnPerPortion": 0,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 38
    },
    {
        "key": 14,
        "cat": "Eierspeisen",
        "name": "Rühr-/Spiegelei",
        "kind": "",
        "harn": 5,
        "harnPerPortion": 7,
        "purin": 2,
        "purinPerPortion": 3,
        "portionG": 130
    },
    {
        "key": 15,
        "cat": "Eierspeisen",
        "name": "Vollei",
        "kind": "",
        "harn": 5,
        "harnPerPortion": 3,
        "purin": 2,
        "purinPerPortion": 1,
        "portionG": 60
    },
    {
        "key": 16,
        "cat": "Fette",
        "name": "Butter",
        "kind": "",
        "harn": 0,
        "harnPerPortion": 0,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 20
    },
    {
        "key": 17,
        "cat": "Fette",
        "name": "Margarine",
        "kind": "",
        "harn": 0,
        "harnPerPortion": 0,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 20
    },
    {
        "key": 18,
        "cat": "Fette",
        "name": "Mayonnaise",
        "kind": "",
        "harn": 1,
        "harnPerPortion": 0,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 25
    },
    {
        "key": 19,
        "cat": "Fisch und Krustentiere",
        "name": "Aal",
        "kind": "Räucherfisch",
        "harn": 68,
        "harnPerPortion": 51,
        "purin": 28,
        "purinPerPortion": 21,
        "portionG": 75
    },
    {
        "key": 20,
        "cat": "Fisch und Krustentiere",
        "name": "Ölsardinen, abgetropft",
        "kind": "Fischkonserve",
        "harn": 319,
        "harnPerPortion": 191,
        "purin": 133,
        "purinPerPortion": 80,
        "portionG": 60
    },
    {
        "key": 21,
        "cat": "Fisch und Krustentiere",
        "name": "Anchovis, Sardellen",
        "kind": "Fischkonserve",
        "harn": 300,
        "harnPerPortion": 150,
        "purin": 125,
        "purinPerPortion": 63,
        "portionG": 50
    },
    {
        "key": 22,
        "cat": "Fisch und Krustentiere",
        "name": "Bismarckhering, abgetropft",
        "kind": "Fischkonserve",
        "harn": 199,
        "harnPerPortion": 129,
        "purin": 83,
        "purinPerPortion": 54,
        "portionG": 65
    },
    {
        "key": 23,
        "cat": "Fisch und Krustentiere",
        "name": "Brathering, abgetropft",
        "kind": "Fischkonserve",
        "harn": 172,
        "harnPerPortion": 258,
        "purin": 72,
        "purinPerPortion": 108,
        "portionG": 150
    },
    {
        "key": 24,
        "cat": "Fisch und Krustentiere",
        "name": "Fischstäbchen",
        "kind": "Fisch gegart",
        "harn": 109,
        "harnPerPortion": 164,
        "purin": 45,
        "purinPerPortion": 68,
        "portionG": 150
    },
    {
        "key": 25,
        "cat": "Fisch und Krustentiere",
        "name": "Forelle",
        "kind": "Fisch gegart",
        "harn": 345,
        "harnPerPortion": 510,
        "purin": 144,
        "purinPerPortion": 213,
        "portionG": 150
    },
    {
        "key": 26,
        "cat": "Fisch und Krustentiere",
        "name": "Forelle",
        "kind": "Räucherfisch",
        "harn": 315,
        "harnPerPortion": 236,
        "purin": 131,
        "purinPerPortion": 98,
        "portionG": 75
    },
    {
        "key": 27,
        "cat": "Fisch und Krustentiere",
        "name": "Heilbutt",
        "kind": "Fisch gegart",
        "harn": 197,
        "harnPerPortion": 296,
        "purin": 82,
        "purinPerPortion": 123,
        "portionG": 150
    },
    {
        "key": 28,
        "cat": "Fisch und Krustentiere",
        "name": "Heilbutt",
        "kind": "Räucherfisch",
        "harn": 180,
        "harnPerPortion": 135,
        "purin": 75,
        "purinPerPortion": 56,
        "portionG": 75
    },
    {
        "key": 29,
        "cat": "Fisch und Krustentiere",
        "name": "Hering",
        "kind": "Fisch gegart",
        "harn": 237,
        "harnPerPortion": 356,
        "purin": 99,
        "purinPerPortion": 148,
        "portionG": 150
    },
    {
        "key": 30,
        "cat": "Fisch und Krustentiere",
        "name": "Kabeljau",
        "kind": "Fisch gegart",
        "harn": 128,
        "harnPerPortion": 192,
        "purin": 53,
        "purinPerPortion": 80,
        "portionG": 150
    },
    {
        "key": 31,
        "cat": "Fisch und Krustentiere",
        "name": "Karpfen",
        "kind": "Fisch gegart",
        "harn": 187,
        "harnPerPortion": 281,
        "purin": 78,
        "purinPerPortion": 117,
        "portionG": 150
    },
    {
        "key": 32,
        "cat": "Fisch und Krustentiere",
        "name": "Kaviar, deutsch",
        "kind": "Fischkonserve",
        "harn": 144,
        "harnPerPortion": 7,
        "purin": 60,
        "purinPerPortion": 3,
        "portionG": 5
    },
    {
        "key": 33,
        "cat": "Fisch und Krustentiere",
        "name": "Krabben, gesalzen",
        "kind": "Fischkonserve",
        "harn": 152,
        "harnPerPortion": 114,
        "purin": 63,
        "purinPerPortion": 48,
        "portionG": 75
    },
    {
        "key": 34,
        "cat": "Fisch und Krustentiere",
        "name": "Lachs",
        "kind": "Räucherfisch",
        "harn": 180,
        "harnPerPortion": 135,
        "purin": 75,
        "purinPerPortion": 56,
        "portionG": 75
    },
    {
        "key": 35,
        "cat": "Fisch und Krustentiere",
        "name": "Makrele, gegart",
        "kind": "Fisch gegart",
        "harn": 164,
        "harnPerPortion": 246,
        "purin": 68,
        "purinPerPortion": 103,
        "portionG": 150
    },
    {
        "key": 36,
        "cat": "Fisch und Krustentiere",
        "name": "Makrele, geräuchert",
        "kind": "Räucherfisch",
        "harn": 153,
        "harnPerPortion": 115,
        "purin": 64,
        "purinPerPortion": 48,
        "portionG": 75
    },
    {
        "key": 37,
        "cat": "Fisch und Krustentiere",
        "name": "Matjesfilet",
        "kind": "Fischkonserve",
        "harn": 228,
        "harnPerPortion": 140,
        "purin": 95,
        "purinPerPortion": 58,
        "portionG": 65
    },
    {
        "key": 38,
        "cat": "Fisch und Krustentiere",
        "name": "Rotbarsch",
        "kind": "Fisch gegart",
        "harn": 150,
        "harnPerPortion": 225,
        "purin": 63,
        "purinPerPortion": 94,
        "portionG": 150
    },
    {
        "key": 39,
        "cat": "Fisch und Krustentiere",
        "name": "Schellfisch",
        "kind": "Fisch gegart",
        "harn": 163,
        "harnPerPortion": 245,
        "purin": 68,
        "purinPerPortion": 102,
        "portionG": 150
    },
    {
        "key": 40,
        "cat": "Fisch und Krustentiere",
        "name": "Schnecken, gegart",
        "kind": "Schalentiere",
        "harn": 116,
        "harnPerPortion": 58,
        "purin": 48,
        "purinPerPortion": 24,
        "portionG": 50
    },
    {
        "key": 41,
        "cat": "Fisch und Krustentiere",
        "name": "Scholle",
        "kind": "Fisch gegart",
        "harn": 151,
        "harnPerPortion": 227,
        "purin": 63,
        "purinPerPortion": 95,
        "portionG": 150
    },
    {
        "key": 42,
        "cat": "Fisch und Krustentiere",
        "name": "Seehecht",
        "kind": "Fisch gegart",
        "harn": 140,
        "harnPerPortion": 210,
        "purin": 58,
        "purinPerPortion": 88,
        "portionG": 150
    },
    {
        "key": 43,
        "cat": "Fisch und Krustentiere",
        "name": "Seelachs",
        "kind": "Fisch gegart",
        "harn": 190,
        "harnPerPortion": 285,
        "purin": 79,
        "purinPerPortion": 119,
        "portionG": 150
    },
    {
        "key": 44,
        "cat": "Fisch und Krustentiere",
        "name": "Sprotten",
        "kind": "Räucherfisch",
        "harn": 463,
        "harnPerPortion": 347,
        "purin": 193,
        "purinPerPortion": 145,
        "portionG": 75
    },
    {
        "key": 45,
        "cat": "Fisch und Krustentiere",
        "name": "Thunfisch in Öl",
        "kind": "Fischkonserve",
        "harn": 148,
        "harnPerPortion": 89,
        "purin": 62,
        "purinPerPortion": 37,
        "portionG": 60
    },
    {
        "key": 46,
        "cat": "Fisch und Krustentiere",
        "name": "Zander",
        "kind": "Fisch gegart",
        "harn": 128,
        "harnPerPortion": 192,
        "purin": 53,
        "purinPerPortion": 80,
        "portionG": 150
    },
    {
        "key": 47,
        "cat": "Fleisch",
        "name": "Bierschinken",
        "kind": "Aufschnitt",
        "harn": 135,
        "harnPerPortion": 41,
        "purin": 56,
        "purinPerPortion": 17,
        "portionG": 30
    },
    {
        "key": 48,
        "cat": "Fleisch",
        "name": "Bockwurst",
        "kind": "Aufschnitt",
        "harn": 93,
        "harnPerPortion": 107,
        "purin": 39,
        "purinPerPortion": 45,
        "portionG": 115
    },
    {
        "key": 49,
        "cat": "Fleisch",
        "name": "Kalbsbraten",
        "kind": "Kalb",
        "harn": 198,
        "harnPerPortion": 248,
        "purin": 83,
        "purinPerPortion": 103,
        "portionG": 125
    },
    {
        "key": 50,
        "cat": "Fleisch",
        "name": "Lammbraten",
        "kind": "Lamm",
        "harn": 176,
        "harnPerPortion": 220,
        "purin": 73,
        "purinPerPortion": 92,
        "portionG": 125
    },
    {
        "key": 51,
        "cat": "Fleisch",
        "name": "Rindsbraten",
        "kind": "Rind",
        "harn": 148,
        "harnPerPortion": 185,
        "purin": 62,
        "purinPerPortion": 77,
        "portionG": 125
    },
    {
        "key": 52,
        "cat": "Fleisch",
        "name": "Schweinebraten",
        "kind": "Schwein",
        "harn": 205,
        "harnPerPortion": 256,
        "purin": 85,
        "purinPerPortion": 107,
        "portionG": 125
    },
    {
        "key": 53,
        "cat": "Fleisch",
        "name": "Brust",
        "kind": "Rind",
        "harn": 118,
        "harnPerPortion": 148,
        "purin": 49,
        "purinPerPortion": 62,
        "portionG": 125
    },
    {
        "key": 54,
        "cat": "Fleisch",
        "name": "Corned Beef",
        "kind": "Aufschnitt",
        "harn": 140,
        "harnPerPortion": 42,
        "purin": 58,
        "purinPerPortion": 18,
        "portionG": 30
    },
    {
        "key": 55,
        "cat": "Fleisch",
        "name": "Entenfleisch, mit Haut",
        "kind": "Geflügel",
        "harn": 160,
        "harnPerPortion": 240,
        "purin": 67,
        "purinPerPortion": 100,
        "portionG": 150
    },
    {
        "key": 56,
        "cat": "Fleisch",
        "name": "Filet",
        "kind": "Rind",
        "harn": 154,
        "harnPerPortion": 193,
        "purin": 64,
        "purinPerPortion": 80,
        "portionG": 125
    },
    {
        "key": 57,
        "cat": "Fleisch",
        "name": "Filet",
        "kind": "Schwein",
        "harn": 212,
        "harnPerPortion": 265,
        "purin": 88,
        "purinPerPortion": 110,
        "portionG": 125
    },
    {
        "key": 58,
        "cat": "Fleisch",
        "name": "Frühstücksfleisch",
        "kind": "Aufschnitt",
        "harn": 102,
        "harnPerPortion": 31,
        "purin": 43,
        "purinPerPortion": 13,
        "portionG": 30
    },
    {
        "key": 59,
        "cat": "Fleisch",
        "name": "Frankfurter Würstchen",
        "kind": "Aufschnitt",
        "harn": 100,
        "harnPerPortion": 100,
        "purin": 42,
        "purinPerPortion": 42,
        "portionG": 100
    },
    {
        "key": 60,
        "cat": "Fleisch",
        "name": "Gänsefleisch, mit Haut",
        "kind": "Geflügel",
        "harn": 254,
        "harnPerPortion": 381,
        "purin": 106,
        "purinPerPortion": 159,
        "portionG": 150
    },
    {
        "key": 61,
        "cat": "Fleisch",
        "name": "Hasenfleisch",
        "kind": "Wild",
        "harn": 154,
        "harnPerPortion": 231,
        "purin": 64,
        "purinPerPortion": 96,
        "portionG": 150
    },
    {
        "key": 62,
        "cat": "Fleisch",
        "name": "Hähnchen, gebraten, mit Haut",
        "kind": "Geflügel",
        "harn": 157,
        "harnPerPortion": 236,
        "purin": 65,
        "purinPerPortion": 98,
        "portionG": 150
    },
    {
        "key": 63,
        "cat": "Fleisch",
        "name": "Hähnchenbrust mit Haut",
        "kind": "Geflügel",
        "harn": 175,
        "harnPerPortion": 263,
        "purin": 73,
        "purinPerPortion": 110,
        "portionG": 150
    },
    {
        "key": 64,
        "cat": "Fleisch",
        "name": "Hähnchenbrust ohne Haut",
        "kind": "Geflügel",
        "harn": 131,
        "harnPerPortion": 197,
        "purin": 55,
        "purinPerPortion": 82,
        "portionG": 150
    },
    {
        "key": 65,
        "cat": "Fleisch",
        "name": "Hühnerbein mit Haut",
        "kind": "Geflügel",
        "harn": 110,
        "harnPerPortion": 165,
        "purin": 46,
        "purinPerPortion": 69,
        "portionG": 150
    },
    {
        "key": 66,
        "cat": "Fleisch",
        "name": "Haxe",
        "kind": "Schwein",
        "harn": 168,
        "harnPerPortion": 210,
        "purin": 70,
        "purinPerPortion": 88,
        "portionG": 125
    },
    {
        "key": 67,
        "cat": "Fleisch",
        "name": "Hirschfleisch",
        "kind": "Wild",
        "harn": 155,
        "harnPerPortion": 233,
        "purin": 65,
        "purinPerPortion": 97,
        "portionG": 150
    },
    {
        "key": 68,
        "cat": "Fleisch",
        "name": "Jagdwurst",
        "kind": "Aufschnitt",
        "harn": 119,
        "harnPerPortion": 36,
        "purin": 50,
        "purinPerPortion": 15,
        "portionG": 30
    },
    {
        "key": 69,
        "cat": "Fleisch",
        "name": "Kalbsbries",
        "kind": "Innereien",
        "harn": 1468,
        "harnPerPortion": 1835,
        "purin": 612,
        "purinPerPortion": 765,
        "portionG": 125
    },
    {
        "key": 70,
        "cat": "Fleisch",
        "name": "Kalbsherz",
        "kind": "Innereien",
        "harn": 210,
        "harnPerPortion": 263,
        "purin": 88,
        "purinPerPortion": 110,
        "portionG": 125
    },
    {
        "key": 71,
        "cat": "Fleisch",
        "name": "Kalbshirn",
        "kind": "Innereien",
        "harn": 118,
        "harnPerPortion": 148,
        "purin": 49,
        "purinPerPortion": 62,
        "portionG": 125
    },
    {
        "key": 72,
        "cat": "Fleisch",
        "name": "Kalbsleber",
        "kind": "Innereien",
        "harn": 287,
        "harnPerPortion": 359,
        "purin": 120,
        "purinPerPortion": 150,
        "portionG": 125
    },
    {
        "key": 73,
        "cat": "Fleisch",
        "name": "Kalbsleberwurst",
        "kind": "Aufschnitt",
        "harn": 155,
        "harnPerPortion": 47,
        "purin": 65,
        "purinPerPortion": 20,
        "portionG": 30
    },
    {
        "key": 74,
        "cat": "Fleisch",
        "name": "Kalbslunge",
        "kind": "Innereien",
        "harn": 280,
        "harnPerPortion": 350,
        "purin": 117,
        "purinPerPortion": 146,
        "portionG": 125
    },
    {
        "key": 75,
        "cat": "Fleisch",
        "name": "Kalbsmilz",
        "kind": "Innereien",
        "harn": 395,
        "harnPerPortion": 494,
        "purin": 165,
        "purinPerPortion": 206,
        "portionG": 125
    },
    {
        "key": 76,
        "cat": "Fleisch",
        "name": "Kalbsniere",
        "kind": "Innereien",
        "harn": 280,
        "harnPerPortion": 350,
        "purin": 117,
        "purinPerPortion": 146,
        "portionG": 125
    },
    {
        "key": 77,
        "cat": "Fleisch",
        "name": "Kaninchenfleisch",
        "kind": "Wild",
        "harn": 132,
        "harnPerPortion": 198,
        "purin": 55,
        "purinPerPortion": 83,
        "portionG": 150
    },
    {
        "key": 78,
        "cat": "Fleisch",
        "name": "Keule",
        "kind": "Kalb",
        "harn": 210,
        "harnPerPortion": 309,
        "purin": 88,
        "purinPerPortion": 129,
        "portionG": 150
    },
    {
        "key": 79,
        "cat": "Fleisch",
        "name": "Keule",
        "kind": "Lamm",
        "harn": 123,
        "harnPerPortion": 308,
        "purin": 51,
        "purinPerPortion": 128,
        "portionG": 250
    },
    {
        "key": 80,
        "cat": "Fleisch",
        "name": "Knackwurst",
        "kind": "Aufschnitt",
        "harn": 91,
        "harnPerPortion": 91,
        "purin": 38,
        "purinPerPortion": 38,
        "portionG": 100
    },
    {
        "key": 81,
        "cat": "Fleisch",
        "name": "Kotelett",
        "kind": "Schwein",
        "harn": 196,
        "harnPerPortion": 294,
        "purin": 82,
        "purinPerPortion": 123,
        "portionG": 150
    },
    {
        "key": 82,
        "cat": "Fleisch",
        "name": "Lachsschinken",
        "kind": "Aufschnitt",
        "harn": 127,
        "harnPerPortion": 38,
        "purin": 53,
        "purinPerPortion": 16,
        "portionG": 30
    },
    {
        "key": 83,
        "cat": "Fleisch",
        "name": "Lachsschinken",
        "kind": "Aufschnitt",
        "harn": 127,
        "harnPerPortion": 38,
        "purin": 53,
        "purinPerPortion": 16,
        "portionG": 30
    },
    {
        "key": 84,
        "cat": "Fleisch",
        "name": "Leberwurst",
        "kind": "Aufschnitt",
        "harn": 131,
        "harnPerPortion": 39,
        "purin": 55,
        "purinPerPortion": 16,
        "portionG": 30
    },
    {
        "key": 85,
        "cat": "Fleisch",
        "name": "Lende",
        "kind": "Kalb",
        "harn": 198,
        "harnPerPortion": 248,
        "purin": 83,
        "purinPerPortion": 103,
        "portionG": 125
    },
    {
        "key": 86,
        "cat": "Fleisch",
        "name": "Mettwurst",
        "kind": "Aufschnitt",
        "harn": 62,
        "harnPerPortion": 19,
        "purin": 26,
        "purinPerPortion": 8,
        "portionG": 30
    },
    {
        "key": 87,
        "cat": "Fleisch",
        "name": "Mortadella, fettarm",
        "kind": "Aufschnitt",
        "harn": 136,
        "harnPerPortion": 41,
        "purin": 57,
        "purinPerPortion": 17,
        "portionG": 30
    },
    {
        "key": 88,
        "cat": "Fleisch",
        "name": "Pferdefleisch",
        "kind": "Pferd",
        "harn": 278,
        "harnPerPortion": 410,
        "purin": 116,
        "purinPerPortion": 171,
        "portionG": 150
    },
    {
        "key": 89,
        "cat": "Fleisch",
        "name": "Presssack",
        "kind": "Aufschnitt",
        "harn": 191,
        "harnPerPortion": 57,
        "purin": 80,
        "purinPerPortion": 24,
        "portionG": 30
    },
    {
        "key": 90,
        "cat": "Fleisch",
        "name": "Putenfleisch, mit Haut",
        "kind": "Geflügel",
        "harn": 219,
        "harnPerPortion": 329,
        "purin": 91,
        "purinPerPortion": 137,
        "portionG": 150
    },
    {
        "key": 91,
        "cat": "Fleisch",
        "name": "Rehfleisch",
        "kind": "Wild",
        "harn": 154,
        "harnPerPortion": 231,
        "purin": 64,
        "purinPerPortion": 96,
        "portionG": 150
    },
    {
        "key": 92,
        "cat": "Fleisch",
        "name": "Rinderleber",
        "kind": "Innereien",
        "harn": 292,
        "harnPerPortion": 365,
        "purin": 122,
        "purinPerPortion": 152,
        "portionG": 125
    },
    {
        "key": 93,
        "cat": "Fleisch",
        "name": "Rinderlunge",
        "kind": "Innereien",
        "harn": 396,
        "harnPerPortion": 495,
        "purin": 165,
        "purinPerPortion": 206,
        "portionG": 125
    },
    {
        "key": 94,
        "cat": "Fleisch",
        "name": "Rinderzunge",
        "kind": "Innereien",
        "harn": 179,
        "harnPerPortion": 224,
        "purin": 75,
        "purinPerPortion": 93,
        "portionG": 125
    },
    {
        "key": 95,
        "cat": "Fleisch",
        "name": "Rostbratwurst",
        "kind": "Aufschnitt",
        "harn": 106,
        "harnPerPortion": 159,
        "purin": 44,
        "purinPerPortion": 66,
        "portionG": 150
    },
    {
        "key": 96,
        "cat": "Fleisch",
        "name": "Salami",
        "kind": "Aufschnitt",
        "harn": 191,
        "harnPerPortion": 57,
        "purin": 80,
        "purinPerPortion": 24,
        "portionG": 30
    },
    {
        "key": 97,
        "cat": "Fleisch",
        "name": "Schinken, gekocht",
        "kind": "Aufschnitt",
        "harn": 131,
        "harnPerPortion": 39,
        "purin": 55,
        "purinPerPortion": 16,
        "portionG": 30
    },
    {
        "key": 98,
        "cat": "Fleisch",
        "name": "Schnitzel",
        "kind": "Schwein",
        "harn": 211,
        "harnPerPortion": 264,
        "purin": 88,
        "purinPerPortion": 110,
        "portionG": 125
    },
    {
        "key": 99,
        "cat": "Fleisch",
        "name": "Schulter",
        "kind": "Kalb",
        "harn": 198,
        "harnPerPortion": 248,
        "purin": 83,
        "purinPerPortion": 103,
        "portionG": 125
    },
    {
        "key": 100,
        "cat": "Fleisch",
        "name": "Schulter",
        "kind": "Rind",
        "harn": 148,
        "harnPerPortion": 185,
        "purin": 62,
        "purinPerPortion": 77,
        "portionG": 125
    },
    {
        "key": 101,
        "cat": "Fleisch",
        "name": "Schulter",
        "kind": "Schwein",
        "harn": 205,
        "harnPerPortion": 308,
        "purin": 85,
        "purinPerPortion": 128,
        "portionG": 150
    },
    {
        "key": 102,
        "cat": "Fleisch",
        "name": "Schweineherz",
        "kind": "Innereien",
        "harn": 210,
        "harnPerPortion": 263,
        "purin": 88,
        "purinPerPortion": 110,
        "portionG": 125
    },
    {
        "key": 103,
        "cat": "Fleisch",
        "name": "Schweinehirn",
        "kind": "Innereien",
        "harn": 94,
        "harnPerPortion": 118,
        "purin": 39,
        "purinPerPortion": 49,
        "portionG": 125
    },
    {
        "key": 104,
        "cat": "Fleisch",
        "name": "Schweineleber",
        "kind": "Innereien",
        "harn": 289,
        "harnPerPortion": 361,
        "purin": 120,
        "purinPerPortion": 150,
        "portionG": 125
    },
    {
        "key": 105,
        "cat": "Fleisch",
        "name": "Schweinemilz",
        "kind": "Innereien",
        "harn": 601,
        "harnPerPortion": 751,
        "purin": 250,
        "purinPerPortion": 313,
        "portionG": 125
    },
    {
        "key": 106,
        "cat": "Fleisch",
        "name": "Schweineniere",
        "kind": "Innereien",
        "harn": 390,
        "harnPerPortion": 488,
        "purin": 163,
        "purinPerPortion": 203,
        "portionG": 125
    },
    {
        "key": 107,
        "cat": "Fleisch",
        "name": "Schweinezunge",
        "kind": "Innereien",
        "harn": 158,
        "harnPerPortion": 198,
        "purin": 66,
        "purinPerPortion": 83,
        "portionG": 125
    },
    {
        "key": 108,
        "cat": "Fleisch",
        "name": "Speck, fett",
        "kind": "Aufschnitt",
        "harn": 120,
        "harnPerPortion": 36,
        "purin": 50,
        "purinPerPortion": 15,
        "portionG": 30
    },
    {
        "key": 109,
        "cat": "Fleisch",
        "name": "Stadtwurst",
        "kind": "Aufschnitt",
        "harn": 85,
        "harnPerPortion": 106,
        "purin": 35,
        "purinPerPortion": 44,
        "portionG": 125
    },
    {
        "key": 110,
        "cat": "Fleisch",
        "name": "Steak",
        "kind": "Rind",
        "harn": 149,
        "harnPerPortion": 224,
        "purin": 62,
        "purinPerPortion": 93,
        "portionG": 150
    },
    {
        "key": 111,
        "cat": "Fleisch",
        "name": "Weißwurst",
        "kind": "Aufschnitt",
        "harn": 102,
        "harnPerPortion": 128,
        "purin": 43,
        "purinPerPortion": 53,
        "portionG": 125
    },
    {
        "key": 112,
        "cat": "Fleisch",
        "name": "Wiener Wüstchen",
        "kind": "Aufschnitt",
        "harn": 96,
        "harnPerPortion": 67,
        "purin": 40,
        "purinPerPortion": 28,
        "portionG": 70
    },
    {
        "key": 113,
        "cat": "Gemüse",
        "name": "Artischocken, gegart",
        "kind": "",
        "harn": 56,
        "harnPerPortion": 84,
        "purin": 23,
        "purinPerPortion": 35,
        "portionG": 150
    },
    {
        "key": 114,
        "cat": "Gemüse",
        "name": "Auberginen, gegart",
        "kind": "",
        "harn": 22,
        "harnPerPortion": 33,
        "purin": 9,
        "purinPerPortion": 14,
        "portionG": 150
    },
    {
        "key": 115,
        "cat": "Gemüse",
        "name": "Birkenpilze",
        "kind": "",
        "harn": 50,
        "harnPerPortion": 100,
        "purin": 21,
        "purinPerPortion": 42,
        "portionG": 200
    },
    {
        "key": 116,
        "cat": "Gemüse",
        "name": "Blaukraut, gegart",
        "kind": "",
        "harn": 41,
        "harnPerPortion": 62,
        "purin": 17,
        "purinPerPortion": 26,
        "portionG": 150
    },
    {
        "key": 117,
        "cat": "Gemüse",
        "name": "Blumenkohl, gegart",
        "kind": "",
        "harn": 45,
        "harnPerPortion": 68,
        "purin": 19,
        "purinPerPortion": 28,
        "portionG": 150
    },
    {
        "key": 118,
        "cat": "Gemüse",
        "name": "Bohnen, grün, gegart",
        "kind": "",
        "harn": 46,
        "harnPerPortion": 69,
        "purin": 19,
        "purinPerPortion": 29,
        "portionG": 150
    },
    {
        "key": 119,
        "cat": "Gemüse",
        "name": "Brokkoli, gegart",
        "kind": "",
        "harn": 53,
        "harnPerPortion": 80,
        "purin": 22,
        "purinPerPortion": 33,
        "portionG": 150
    },
    {
        "key": 120,
        "cat": "Gemüse",
        "name": "Champignons, gegart",
        "kind": "",
        "harn": 67,
        "harnPerPortion": 67,
        "purin": 28,
        "purinPerPortion": 28,
        "portionG": 100
    },
    {
        "key": 121,
        "cat": "Gemüse",
        "name": "Chicoree",
        "kind": "",
        "harn": 15,
        "harnPerPortion": 8,
        "purin": 6,
        "purinPerPortion": 3,
        "portionG": 50
    },
    {
        "key": 122,
        "cat": "Gemüse",
        "name": "Chinakohl",
        "kind": "",
        "harn": 25,
        "harnPerPortion": 38,
        "purin": 10,
        "purinPerPortion": 16,
        "portionG": 150
    },
    {
        "key": 123,
        "cat": "Gemüse",
        "name": "Endiviensalat",
        "kind": "",
        "harn": 11,
        "harnPerPortion": 6,
        "purin": 5,
        "purinPerPortion": 3,
        "portionG": 50
    },
    {
        "key": 124,
        "cat": "Gemüse",
        "name": "Feldsalat",
        "kind": "",
        "harn": 24,
        "harnPerPortion": 12,
        "purin": 10,
        "purinPerPortion": 5,
        "portionG": 50
    },
    {
        "key": 125,
        "cat": "Gemüse",
        "name": "Fenchel, gegart",
        "kind": "",
        "harn": 18,
        "harnPerPortion": 27,
        "purin": 8,
        "purinPerPortion": 11,
        "portionG": 150
    },
    {
        "key": 126,
        "cat": "Gemüse",
        "name": "Karotten",
        "kind": "",
        "harn": 15,
        "harnPerPortion": 23,
        "purin": 6,
        "purinPerPortion": 10,
        "portionG": 150
    },
    {
        "key": 127,
        "cat": "Gemüse",
        "name": "Karotten, gegart",
        "kind": "",
        "harn": 16,
        "harnPerPortion": 24,
        "purin": 7,
        "purinPerPortion": 10,
        "portionG": 150
    },
    {
        "key": 128,
        "cat": "Gemüse",
        "name": "Kohlrabi",
        "kind": "",
        "harn": 30,
        "harnPerPortion": 45,
        "purin": 13,
        "purinPerPortion": 19,
        "portionG": 150
    },
    {
        "key": 129,
        "cat": "Gemüse",
        "name": "Kohlrabi, gegart",
        "kind": "",
        "harn": 32,
        "harnPerPortion": 48,
        "purin": 13,
        "purinPerPortion": 20,
        "portionG": 150
    },
    {
        "key": 130,
        "cat": "Gemüse",
        "name": "Kopfsalat",
        "kind": "",
        "harn": 10,
        "harnPerPortion": 5,
        "purin": 4,
        "purinPerPortion": 2,
        "portionG": 50
    },
    {
        "key": 131,
        "cat": "Gemüse",
        "name": "Kresse",
        "kind": "",
        "harn": 30,
        "harnPerPortion": 45,
        "purin": 13,
        "purinPerPortion": 19,
        "portionG": 150
    },
    {
        "key": 132,
        "cat": "Gemüse",
        "name": "Lauch",
        "kind": "",
        "harn": 40,
        "harnPerPortion": 60,
        "purin": 17,
        "purinPerPortion": 25,
        "portionG": 150
    },
    {
        "key": 133,
        "cat": "Gemüse",
        "name": "Lauch, gegart",
        "kind": "",
        "harn": 45,
        "harnPerPortion": 68,
        "purin": 19,
        "purinPerPortion": 28,
        "portionG": 150
    },
    {
        "key": 134,
        "cat": "Gemüse",
        "name": "Mais, gegart",
        "kind": "",
        "harn": 47,
        "harnPerPortion": 71,
        "purin": 20,
        "purinPerPortion": 30,
        "portionG": 150
    },
    {
        "key": 135,
        "cat": "Gemüse",
        "name": "Morcheln",
        "kind": "",
        "harn": 30,
        "harnPerPortion": 60,
        "purin": 13,
        "purinPerPortion": 25,
        "portionG": 200
    },
    {
        "key": 136,
        "cat": "Gemüse",
        "name": "Oliven",
        "kind": "",
        "harn": 25,
        "harnPerPortion": 5,
        "purin": 10,
        "purinPerPortion": 2,
        "portionG": 20
    },
    {
        "key": 137,
        "cat": "Gemüse",
        "name": "Paprika",
        "kind": "",
        "harn": 10,
        "harnPerPortion": 15,
        "purin": 4,
        "purinPerPortion": 6,
        "portionG": 150
    },
    {
        "key": 138,
        "cat": "Gemüse",
        "name": "Pfifferlinge",
        "kind": "",
        "harn": 30,
        "harnPerPortion": 60,
        "purin": 13,
        "purinPerPortion": 25,
        "portionG": 200
    },
    {
        "key": 139,
        "cat": "Gemüse",
        "name": "Radieschen",
        "kind": "",
        "harn": 10,
        "harnPerPortion": 10,
        "purin": 4,
        "purinPerPortion": 4,
        "portionG": 100
    },
    {
        "key": 140,
        "cat": "Gemüse",
        "name": "Rettich",
        "kind": "",
        "harn": 10,
        "harnPerPortion": 15,
        "purin": 4,
        "purinPerPortion": 6,
        "portionG": 150
    },
    {
        "key": 141,
        "cat": "Gemüse",
        "name": "Rosenkohl, gegart",
        "kind": "",
        "harn": 56,
        "harnPerPortion": 84,
        "purin": 23,
        "purinPerPortion": 35,
        "portionG": 150
    },
    {
        "key": 142,
        "cat": "Gemüse",
        "name": "Rote Beete, gegart",
        "kind": "",
        "harn": 21,
        "harnPerPortion": 32,
        "purin": 9,
        "purinPerPortion": 13,
        "portionG": 150
    },
    {
        "key": 143,
        "cat": "Gemüse",
        "name": "Salatgurke",
        "kind": "",
        "harn": 8,
        "harnPerPortion": 12,
        "purin": 3,
        "purinPerPortion": 5,
        "portionG": 150
    },
    {
        "key": 144,
        "cat": "Gemüse",
        "name": "Sauerkraut, gegart",
        "kind": "",
        "harn": 22,
        "harnPerPortion": 33,
        "purin": 9,
        "purinPerPortion": 14,
        "portionG": 150
    },
    {
        "key": 145,
        "cat": "Gemüse",
        "name": "Schnittlauch",
        "kind": "",
        "harn": 30,
        "harnPerPortion": 2,
        "purin": 13,
        "purinPerPortion": 1,
        "portionG": 5
    },
    {
        "key": 146,
        "cat": "Gemüse",
        "name": "Schwarzwurzeln, gegart",
        "kind": "",
        "harn": 74,
        "harnPerPortion": 111,
        "purin": 31,
        "purinPerPortion": 46,
        "portionG": 150
    },
    {
        "key": 147,
        "cat": "Gemüse",
        "name": "Sellerie (Knolle)",
        "kind": "",
        "harn": 30,
        "harnPerPortion": 45,
        "purin": 13,
        "purinPerPortion": 19,
        "portionG": 150
    },
    {
        "key": 148,
        "cat": "Gemüse",
        "name": "Sellerie (Knolle), gegart",
        "kind": "",
        "harn": 30,
        "harnPerPortion": 45,
        "purin": 13,
        "purinPerPortion": 19,
        "portionG": 150
    },
    {
        "key": 149,
        "cat": "Gemüse",
        "name": "Spargel, gegart",
        "kind": "",
        "harn": 28,
        "harnPerPortion": 42,
        "purin": 12,
        "purinPerPortion": 18,
        "portionG": 150
    },
    {
        "key": 150,
        "cat": "Gemüse",
        "name": "Spinat, gegart",
        "kind": "",
        "harn": 71,
        "harnPerPortion": 107,
        "purin": 30,
        "purinPerPortion": 45,
        "portionG": 150
    },
    {
        "key": 151,
        "cat": "Gemüse",
        "name": "Steinpilze",
        "kind": "",
        "harn": 80,
        "harnPerPortion": 160,
        "purin": 33,
        "purinPerPortion": 67,
        "portionG": 200
    },
    {
        "key": 152,
        "cat": "Gemüse",
        "name": "Tomaten",
        "kind": "",
        "harn": 10,
        "harnPerPortion": 15,
        "purin": 4,
        "purinPerPortion": 6,
        "portionG": 150
    },
    {
        "key": 153,
        "cat": "Gemüse",
        "name": "Weißkraut",
        "kind": "",
        "harn": 20,
        "harnPerPortion": 30,
        "purin": 8,
        "purinPerPortion": 13,
        "portionG": 150
    },
    {
        "key": 154,
        "cat": "Gemüse",
        "name": "Weißkraut, gegart",
        "kind": "",
        "harn": 21,
        "harnPerPortion": 32,
        "purin": 9,
        "purinPerPortion": 13,
        "portionG": 150
    },
    {
        "key": 155,
        "cat": "Gemüse",
        "name": "Wirsing, gegart",
        "kind": "",
        "harn": 41,
        "harnPerPortion": 62,
        "purin": 17,
        "purinPerPortion": 26,
        "portionG": 150
    },
    {
        "key": 156,
        "cat": "Gemüse",
        "name": "Zucchini, gegart",
        "kind": "",
        "harn": 22,
        "harnPerPortion": 33,
        "purin": 9,
        "purinPerPortion": 14,
        "portionG": 150
    },
    {
        "key": 157,
        "cat": "Gemüse",
        "name": "Zwiebeln",
        "kind": "",
        "harn": 15,
        "harnPerPortion": 5,
        "purin": 6,
        "purinPerPortion": 2,
        "portionG": 30
    },
    {
        "key": 158,
        "cat": "Getränke alkoholfrei",
        "name": "Apfelsaft",
        "kind": "",
        "harn": 16,
        "harnPerPortion": 32,
        "purin": 7,
        "purinPerPortion": 13,
        "portionG": 20
    },
    {
        "key": 159,
        "cat": "Getränke alkoholfrei",
        "name": "Apfelsaftschorle (1:1)",
        "kind": "",
        "harn": 8,
        "harnPerPortion": 16,
        "purin": 3,
        "purinPerPortion": 7,
        "portionG": 200
    },
    {
        "key": 160,
        "cat": "Getränke alkoholfrei",
        "name": "Bier, hell, alkoholfrei",
        "kind": "",
        "harn": 10,
        "harnPerPortion": 33,
        "purin": 4,
        "purinPerPortion": 14,
        "portionG": 330
    },
    {
        "key": 161,
        "cat": "Getränke alkoholfrei",
        "name": "Cola Mix",
        "kind": "",
        "harn": 5,
        "harnPerPortion": 10,
        "purin": 2,
        "purinPerPortion": 4,
        "portionG": 200
    },
    {
        "key": 162,
        "cat": "Getränke alkoholfrei",
        "name": "Colagetränk light, koffeinhaltig",
        "kind": "",
        "harn": 0,
        "harnPerPortion": 0,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 200
    },
    {
        "key": 163,
        "cat": "Getränke alkoholfrei",
        "name": "Colagetränk, koffeinhaltig",
        "kind": "",
        "harn": 10,
        "harnPerPortion": 20,
        "purin": 4,
        "purinPerPortion": 8,
        "portionG": 200
    },
    {
        "key": 164,
        "cat": "Getränke alkoholfrei",
        "name": "Grapefruitsaft",
        "kind": "",
        "harn": 15,
        "harnPerPortion": 30,
        "purin": 6,
        "purinPerPortion": 13,
        "portionG": 200
    },
    {
        "key": 165,
        "cat": "Getränke alkoholfrei",
        "name": "Karottensaft",
        "kind": "",
        "harn": 16,
        "harnPerPortion": 32,
        "purin": 7,
        "purinPerPortion": 13,
        "portionG": 200
    },
    {
        "key": 166,
        "cat": "Getränke alkoholfrei",
        "name": "Limonaden mit Fruchtgeschmack",
        "kind": "",
        "harn": 0,
        "harnPerPortion": 0,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 200
    },
    {
        "key": 167,
        "cat": "Getränke alkoholfrei",
        "name": "Multivitaminsaft",
        "kind": "",
        "harn": 16,
        "harnPerPortion": 32,
        "purin": 7,
        "purinPerPortion": 13,
        "portionG": 200
    },
    {
        "key": 168,
        "cat": "Getränke alkoholfrei",
        "name": "Orangensaft",
        "kind": "",
        "harn": 21,
        "harnPerPortion": 42,
        "purin": 9,
        "purinPerPortion": 18,
        "portionG": 200
    },
    {
        "key": 169,
        "cat": "Getränke alkoholfrei",
        "name": "Tee, Kaffee",
        "kind": "",
        "harn": 0,
        "harnPerPortion": 0,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 200
    },
    {
        "key": 170,
        "cat": "Getränke alkoholfrei",
        "name": "Tomatensaft",
        "kind": "",
        "harn": 4,
        "harnPerPortion": 8,
        "purin": 2,
        "purinPerPortion": 3,
        "portionG": 200
    },
    {
        "key": 171,
        "cat": "Getränke alkoholhaltig",
        "name": "Altbier",
        "kind": "",
        "harn": 12,
        "harnPerPortion": 40,
        "purin": 5,
        "purinPerPortion": 17,
        "portionG": 330
    },
    {
        "key": 172,
        "cat": "Getränke alkoholhaltig",
        "name": "Bier, hell",
        "kind": "",
        "harn": 15,
        "harnPerPortion": 50,
        "purin": 6,
        "purinPerPortion": 21,
        "portionG": 330
    },
    {
        "key": 173,
        "cat": "Getränke alkoholhaltig",
        "name": "Doppelbock",
        "kind": "",
        "harn": 14,
        "harnPerPortion": 46,
        "purin": 6,
        "purinPerPortion": 19,
        "portionG": 330
    },
    {
        "key": 174,
        "cat": "Getränke alkoholhaltig",
        "name": "Hefeweißbier",
        "kind": "",
        "harn": 15,
        "harnPerPortion": 50,
        "purin": 6,
        "purinPerPortion": 21,
        "portionG": 330
    },
    {
        "key": 175,
        "cat": "Getränke alkoholhaltig",
        "name": "Kölsch",
        "kind": "",
        "harn": 12,
        "harnPerPortion": 40,
        "purin": 5,
        "purinPerPortion": 17,
        "portionG": 330
    },
    {
        "key": 176,
        "cat": "Getränke alkoholhaltig",
        "name": "Pils",
        "kind": "",
        "harn": 10,
        "harnPerPortion": 33,
        "purin": 4,
        "purinPerPortion": 14,
        "portionG": 330
    },
    {
        "key": 177,
        "cat": "Getränke alkoholhaltig",
        "name": "Rotwein",
        "kind": "",
        "harn": 0,
        "harnPerPortion": 0,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 125
    },
    {
        "key": 178,
        "cat": "Getränke alkoholhaltig",
        "name": "Sekt",
        "kind": "",
        "harn": 0,
        "harnPerPortion": 0,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 100
    },
    {
        "key": 179,
        "cat": "Getränke alkoholhaltig",
        "name": "Weißwein",
        "kind": "",
        "harn": 0,
        "harnPerPortion": 0,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 125
    },
    {
        "key": 180,
        "cat": "Getreideerzeugnisse",
        "name": "Buchweizen, gegart",
        "kind": "",
        "harn": 59,
        "harnPerPortion": 47,
        "purin": 25,
        "purinPerPortion": 20,
        "portionG": 80
    },
    {
        "key": 181,
        "cat": "Getreideerzeugnisse",
        "name": "Cornflakes",
        "kind": "",
        "harn": 80,
        "harnPerPortion": 24,
        "purin": 33,
        "purinPerPortion": 10,
        "portionG": 30
    },
    {
        "key": 182,
        "cat": "Getreideerzeugnisse",
        "name": "Eierteigwaren, gegart",
        "kind": "",
        "harn": 21,
        "harnPerPortion": 26,
        "purin": 9,
        "purinPerPortion": 11,
        "portionG": 125
    },
    {
        "key": 183,
        "cat": "Getreideerzeugnisse",
        "name": "Gerstengraupen, gegart",
        "kind": "",
        "harn": 21,
        "harnPerPortion": 17,
        "purin": 9,
        "purinPerPortion": 7,
        "portionG": 80
    },
    {
        "key": 184,
        "cat": "Getreideerzeugnisse",
        "name": "Grünkern, gegart",
        "kind": "",
        "harn": 49,
        "harnPerPortion": 39,
        "purin": 20,
        "purinPerPortion": 16,
        "portionG": 80
    },
    {
        "key": 185,
        "cat": "Getreideerzeugnisse",
        "name": "Grieß, gegart",
        "kind": "",
        "harn": 9,
        "harnPerPortion": 16,
        "purin": 4,
        "purinPerPortion": 7,
        "portionG": 180
    },
    {
        "key": 186,
        "cat": "Getreideerzeugnisse",
        "name": "Haferflocken, gegart",
        "kind": "",
        "harn": 26,
        "harnPerPortion": 10,
        "purin": 11,
        "purinPerPortion": 4,
        "portionG": 40
    },
    {
        "key": 187,
        "cat": "Getreideerzeugnisse",
        "name": "Hirse, gegart",
        "kind": "",
        "harn": 33,
        "harnPerPortion": 26,
        "purin": 14,
        "purinPerPortion": 11,
        "portionG": 80
    },
    {
        "key": 188,
        "cat": "Getreideerzeugnisse",
        "name": "Mohn, gemahlen",
        "kind": "",
        "harn": 172,
        "harnPerPortion": 34,
        "purin": 72,
        "purinPerPortion": 14,
        "portionG": 20
    },
    {
        "key": 189,
        "cat": "Getreideerzeugnisse",
        "name": "Reis, parboiled, gegart",
        "kind": "",
        "harn": 32,
        "harnPerPortion": 58,
        "purin": 13,
        "purinPerPortion": 24,
        "portionG": 180
    },
    {
        "key": 190,
        "cat": "Getreideerzeugnisse",
        "name": "Sago",
        "kind": "",
        "harn": 4,
        "harnPerPortion": 0,
        "purin": 2,
        "purinPerPortion": 0,
        "portionG": 10
    },
    {
        "key": 191,
        "cat": "Getreideerzeugnisse",
        "name": "Teigwaren aus Hartweizengrieß, gegart",
        "kind": "",
        "harn": 26,
        "harnPerPortion": 33,
        "purin": 11,
        "purinPerPortion": 14,
        "portionG": 125
    },
    {
        "key": 192,
        "cat": "Getreideerzeugnisse",
        "name": "Vollkornnudeln, gegart",
        "kind": "",
        "harn": 34,
        "harnPerPortion": 43,
        "purin": 14,
        "purinPerPortion": 18,
        "portionG": 125
    },
    {
        "key": 193,
        "cat": "Getreideerzeugnisse",
        "name": "Weizenmehl Typ 405",
        "kind": "",
        "harn": 40,
        "harnPerPortion": 8,
        "purin": 17,
        "purinPerPortion": 3,
        "portionG": 20
    },
    {
        "key": 194,
        "cat": "Hülsenfrüchte",
        "name": "Bohnen, dick (Saubohnen), gegart",
        "kind": "",
        "harn": 55,
        "harnPerPortion": 83,
        "purin": 23,
        "purinPerPortion": 35,
        "portionG": 150
    },
    {
        "key": 195,
        "cat": "Hülsenfrüchte",
        "name": "Bohnen, weiß, gegart",
        "kind": "",
        "harn": 77,
        "harnPerPortion": 116,
        "purin": 32,
        "purinPerPortion": 48,
        "portionG": 150
    },
    {
        "key": 196,
        "cat": "Hülsenfrüchte",
        "name": "Erbsen, grün",
        "kind": "",
        "harn": 171,
        "harnPerPortion": 257,
        "purin": 71,
        "purinPerPortion": 107,
        "portionG": 150
    },
    {
        "key": 197,
        "cat": "Hülsenfrüchte",
        "name": "Kichererbsen, reif, gegart",
        "kind": "",
        "harn": 55,
        "harnPerPortion": 83,
        "purin": 23,
        "purinPerPortion": 35,
        "portionG": 150
    },
    {
        "key": 198,
        "cat": "Hülsenfrüchte",
        "name": "Linsen, reif, gegart",
        "kind": "",
        "harn": 75,
        "harnPerPortion": 113,
        "purin": 31,
        "purinPerPortion": 47,
        "portionG": 150
    },
    {
        "key": 199,
        "cat": "Hülsenfrüchte",
        "name": "Sojabohnen, gegart",
        "kind": "",
        "harn": 81,
        "harnPerPortion": 49,
        "purin": 34,
        "purinPerPortion": 20,
        "portionG": 60
    },
    {
        "key": 200,
        "cat": "Hülsenfrüchte",
        "name": "Tofu",
        "kind": "",
        "harn": 70,
        "harnPerPortion": 70,
        "purin": 29,
        "purinPerPortion": 29,
        "portionG": 100
    },
    {
        "key": 201,
        "cat": "Hülsenfruechte",
        "name": "Sojasoße, Fertigprodukt",
        "kind": "",
        "harn": 41,
        "harnPerPortion": 8,
        "purin": 17,
        "purinPerPortion": 3,
        "portionG": 20
    },
    {
        "key": 202,
        "cat": "Kartoffeln",
        "name": "Bratkartoffeln, gegart",
        "kind": "",
        "harn": 14,
        "harnPerPortion": 35,
        "purin": 6,
        "purinPerPortion": 15,
        "portionG": 250
    },
    {
        "key": 203,
        "cat": "Kartoffeln",
        "name": "Kartoffelchips",
        "kind": "",
        "harn": 70,
        "harnPerPortion": 18,
        "purin": 29,
        "purinPerPortion": 8,
        "portionG": 25
    },
    {
        "key": 204,
        "cat": "Kartoffeln",
        "name": "Kartoffelknödel, gegart",
        "kind": "",
        "harn": 18,
        "harnPerPortion": 28,
        "purin": 8,
        "purinPerPortion": 12,
        "portionG": 200
    },
    {
        "key": 205,
        "cat": "Kartoffeln",
        "name": "Kartoffeln, geschält, gegart",
        "kind": "",
        "harn": 15,
        "harnPerPortion": 30,
        "purin": 6,
        "purinPerPortion": 13,
        "portionG": 200
    },
    {
        "key": 206,
        "cat": "Kartoffeln",
        "name": "Kartoffeln, ungeschält, gegart",
        "kind": "",
        "harn": 10,
        "harnPerPortion": 25,
        "purin": 4,
        "purinPerPortion": 10,
        "portionG": 240
    },
    {
        "key": 207,
        "cat": "Kartoffeln",
        "name": "Kartoffelpüree, gegart",
        "kind": "",
        "harn": 11,
        "harnPerPortion": 28,
        "purin": 5,
        "purinPerPortion": 12,
        "portionG": 250
    },
    {
        "key": 208,
        "cat": "Kartoffeln",
        "name": "Kartoffelpuffer, gegart",
        "kind": "",
        "harn": 18,
        "harnPerPortion": 38,
        "purin": 8,
        "purinPerPortion": 16,
        "portionG": 200
    },
    {
        "key": 209,
        "cat": "Kartoffeln",
        "name": "Kartoffelsalat mit Öl",
        "kind": "",
        "harn": 12,
        "harnPerPortion": 38,
        "purin": 5,
        "purinPerPortion": 16,
        "portionG": 250
    },
    {
        "key": 210,
        "cat": "Kartoffeln",
        "name": "Kroketten, gegart",
        "kind": "",
        "harn": 16,
        "harnPerPortion": 40,
        "purin": 7,
        "purinPerPortion": 17,
        "portionG": 250
    },
    {
        "key": 211,
        "cat": "Kartoffeln",
        "name": "Pommes frites, gegart",
        "kind": "",
        "harn": 18,
        "harnPerPortion": 26,
        "purin": 8,
        "purinPerPortion": 11,
        "portionG": 200
    },
    {
        "key": 212,
        "cat": "Konserven",
        "name": "Blaukraut",
        "kind": "",
        "harn": 42,
        "harnPerPortion": 63,
        "purin": 18,
        "purinPerPortion": 26,
        "portionG": 150
    },
    {
        "key": 213,
        "cat": "Konserven",
        "name": "Blumenkohl",
        "kind": "",
        "harn": 47,
        "harnPerPortion": 71,
        "purin": 20,
        "purinPerPortion": 30,
        "portionG": 150
    },
    {
        "key": 214,
        "cat": "Konserven",
        "name": "Bohnen, grün",
        "kind": "",
        "harn": 62,
        "harnPerPortion": 62,
        "purin": 26,
        "purinPerPortion": 26,
        "portionG": 100
    },
    {
        "key": 215,
        "cat": "Konserven",
        "name": "Champignons",
        "kind": "",
        "harn": 44,
        "harnPerPortion": 66,
        "purin": 18,
        "purinPerPortion": 28,
        "portionG": 150
    },
    {
        "key": 216,
        "cat": "Konserven",
        "name": "Gewürzgurken",
        "kind": "",
        "harn": 8,
        "harnPerPortion": 8,
        "purin": 3,
        "purinPerPortion": 3,
        "portionG": 100
    },
    {
        "key": 217,
        "cat": "Konserven",
        "name": "Mais",
        "kind": "",
        "harn": 45,
        "harnPerPortion": 68,
        "purin": 19,
        "purinPerPortion": 28,
        "portionG": 150
    },
    {
        "key": 218,
        "cat": "Konserven",
        "name": "Mixed Pickles",
        "kind": "",
        "harn": 16,
        "harnPerPortion": 32,
        "purin": 7,
        "purinPerPortion": 13,
        "portionG": 200
    },
    {
        "key": 219,
        "cat": "Konserven",
        "name": "Paprika",
        "kind": "",
        "harn": 11,
        "harnPerPortion": 17,
        "purin": 5,
        "purinPerPortion": 7,
        "portionG": 150
    },
    {
        "key": 220,
        "cat": "Konserven",
        "name": "Pfifferlinge",
        "kind": "",
        "harn": 31,
        "harnPerPortion": 62,
        "purin": 13,
        "purinPerPortion": 26,
        "portionG": 200
    },
    {
        "key": 221,
        "cat": "Konserven",
        "name": "Sauerkraut",
        "kind": "",
        "harn": 20,
        "harnPerPortion": 30,
        "purin": 8,
        "purinPerPortion": 13,
        "portionG": 150
    },
    {
        "key": 222,
        "cat": "Konserven",
        "name": "Sojawürstchen",
        "kind": "",
        "harn": 17,
        "harnPerPortion": 17,
        "purin": 7,
        "purinPerPortion": 7,
        "portionG": 100
    },
    {
        "key": 223,
        "cat": "Konserven",
        "name": "Tomaten",
        "kind": "",
        "harn": 11,
        "harnPerPortion": 9,
        "purin": 5,
        "purinPerPortion": 4,
        "portionG": 80
    },
    {
        "key": 224,
        "cat": "Milchprodukte",
        "name": "Bergkäse 45% F.i.Tr",
        "kind": "",
        "harn": 10,
        "harnPerPortion": 3,
        "purin": 4,
        "purinPerPortion": 1,
        "portionG": 30
    },
    {
        "key": 225,
        "cat": "Milchprodukte",
        "name": "Butterkäse 45% F.i.Tr.",
        "kind": "",
        "harn": 10,
        "harnPerPortion": 3,
        "purin": 4,
        "purinPerPortion": 1,
        "portionG": 30
    },
    {
        "key": 226,
        "cat": "Milchprodukte",
        "name": "Buttermilch",
        "kind": "",
        "harn": 0,
        "harnPerPortion": 0,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 150
    },
    {
        "key": 227,
        "cat": "Milchprodukte",
        "name": "Camembert 45% F.i.Tr.",
        "kind": "",
        "harn": 10,
        "harnPerPortion": 3,
        "purin": 4,
        "purinPerPortion": 1,
        "portionG": 30
    },
    {
        "key": 228,
        "cat": "Milchprodukte",
        "name": "Dickmilch 1,5% Fett",
        "kind": "",
        "harn": 0,
        "harnPerPortion": 0,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 150
    },
    {
        "key": 229,
        "cat": "Milchprodukte",
        "name": "Edamer 45% F.i.Tr.",
        "kind": "",
        "harn": 10,
        "harnPerPortion": 3,
        "purin": 4,
        "purinPerPortion": 1,
        "portionG": 30
    },
    {
        "key": 230,
        "cat": "Milchprodukte",
        "name": "Emmentaler 45% F.i.Tr.",
        "kind": "",
        "harn": 10,
        "harnPerPortion": 3,
        "purin": 4,
        "purinPerPortion": 1,
        "portionG": 30
    },
    {
        "key": 231,
        "cat": "Milchprodukte",
        "name": "Feta",
        "kind": "",
        "harn": 30,
        "harnPerPortion": 9,
        "purin": 13,
        "purinPerPortion": 4,
        "portionG": 30
    },
    {
        "key": 232,
        "cat": "Milchprodukte",
        "name": "Gouda 45% F.i.Tr.",
        "kind": "",
        "harn": 10,
        "harnPerPortion": 3,
        "purin": 4,
        "purinPerPortion": 1,
        "portionG": 30
    },
    {
        "key": 233,
        "cat": "Milchprodukte",
        "name": "Joghurt 1,5% Fett",
        "kind": "",
        "harn": 0,
        "harnPerPortion": 0,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 150
    },
    {
        "key": 234,
        "cat": "Milchprodukte",
        "name": "Kefir 1,5% Fett",
        "kind": "",
        "harn": 0,
        "harnPerPortion": 0,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 150
    },
    {
        "key": 235,
        "cat": "Milchprodukte",
        "name": "Limburger 45% F.i.Tr.",
        "kind": "",
        "harn": 10,
        "harnPerPortion": 3,
        "purin": 4,
        "purinPerPortion": 1,
        "portionG": 30
    },
    {
        "key": 236,
        "cat": "Milchprodukte",
        "name": "Mozarella",
        "kind": "",
        "harn": 10,
        "harnPerPortion": 10,
        "purin": 4,
        "purinPerPortion": 4,
        "portionG": 100
    },
    {
        "key": 237,
        "cat": "Milchprodukte",
        "name": "Quark 20% F.i.Tr.",
        "kind": "",
        "harn": 0,
        "harnPerPortion": 0,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 30
    },
    {
        "key": 238,
        "cat": "Milchprodukte",
        "name": "Schmelzkäse 45% F.i.Tr.",
        "kind": "",
        "harn": 14,
        "harnPerPortion": 4,
        "purin": 6,
        "purinPerPortion": 2,
        "portionG": 30
    },
    {
        "key": 239,
        "cat": "Milchprodukte",
        "name": "Tilsiter 45% F.i.Tr.",
        "kind": "",
        "harn": 10,
        "harnPerPortion": 3,
        "purin": 4,
        "purinPerPortion": 1,
        "portionG": 30
    },
    {
        "key": 240,
        "cat": "Milchprodukte",
        "name": "Trinkmilch 1,5 u. 3,5% Fett",
        "kind": "",
        "harn": 0,
        "harnPerPortion": 0,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 150
    },
    {
        "key": 241,
        "cat": "Nüsse",
        "name": "Erdnüsse, geröstet und gesalzen",
        "kind": "",
        "harn": 70,
        "harnPerPortion": 70,
        "purin": 29,
        "purinPerPortion": 29,
        "portionG": 100
    },
    {
        "key": 242,
        "cat": "Nüsse",
        "name": "Haselnüsse",
        "kind": "",
        "harn": 40,
        "harnPerPortion": 24,
        "purin": 17,
        "purinPerPortion": 10,
        "portionG": 60
    },
    {
        "key": 243,
        "cat": "Nüsse",
        "name": "Mandeln, süß",
        "kind": "",
        "harn": 40,
        "harnPerPortion": 24,
        "purin": 17,
        "purinPerPortion": 10,
        "portionG": 60
    },
    {
        "key": 244,
        "cat": "Nüsse",
        "name": "Paranüsse",
        "kind": "",
        "harn": 22,
        "harnPerPortion": 13,
        "purin": 9,
        "purinPerPortion": 5,
        "portionG": 60
    },
    {
        "key": 245,
        "cat": "Nüsse",
        "name": "Sesamsamen",
        "kind": "",
        "harn": 80,
        "harnPerPortion": 16,
        "purin": 33,
        "purinPerPortion": 7,
        "portionG": 20
    },
    {
        "key": 246,
        "cat": "Nüsse",
        "name": "Sonnenblumenkerne",
        "kind": "",
        "harn": 60,
        "harnPerPortion": 32,
        "purin": 25,
        "purinPerPortion": 13,
        "portionG": 20
    },
    {
        "key": 247,
        "cat": "Nüsse",
        "name": "Walnüsse",
        "kind": "",
        "harn": 25,
        "harnPerPortion": 15,
        "purin": 10,
        "purinPerPortion": 6,
        "portionG": 60
    },
    {
        "key": 248,
        "cat": "Obst",
        "name": "Äpfel (Trockenobst)",
        "kind": "",
        "harn": 80,
        "harnPerPortion": 20,
        "purin": 33,
        "purinPerPortion": 8,
        "portionG": 25
    },
    {
        "key": 249,
        "cat": "Obst",
        "name": "Ananas",
        "kind": "",
        "harn": 20,
        "harnPerPortion": 25,
        "purin": 8,
        "purinPerPortion": 10,
        "portionG": 125
    },
    {
        "key": 250,
        "cat": "Obst",
        "name": "Apfel",
        "kind": "",
        "harn": 15,
        "harnPerPortion": 19,
        "purin": 6,
        "purinPerPortion": 8,
        "portionG": 125
    },
    {
        "key": 251,
        "cat": "Obst",
        "name": "Aprikosen",
        "kind": "",
        "harn": 20,
        "harnPerPortion": 10,
        "purin": 8,
        "purinPerPortion": 4,
        "portionG": 50
    },
    {
        "key": 252,
        "cat": "Obst",
        "name": "Aprikosen (Trockenobst)",
        "kind": "",
        "harn": 118,
        "harnPerPortion": 30,
        "purin": 49,
        "purinPerPortion": 13,
        "portionG": 25
    },
    {
        "key": 253,
        "cat": "Obst",
        "name": "Avocado",
        "kind": "",
        "harn": 30,
        "harnPerPortion": 68,
        "purin": 13,
        "purinPerPortion": 28,
        "portionG": 225
    },
    {
        "key": 254,
        "cat": "Obst",
        "name": "Bananen",
        "kind": "",
        "harn": 25,
        "harnPerPortion": 31,
        "purin": 10,
        "purinPerPortion": 13,
        "portionG": 125
    },
    {
        "key": 255,
        "cat": "Obst",
        "name": "Birnen",
        "kind": "",
        "harn": 15,
        "harnPerPortion": 19,
        "purin": 6,
        "purinPerPortion": 8,
        "portionG": 125
    },
    {
        "key": 256,
        "cat": "Obst",
        "name": "Brombeeren",
        "kind": "",
        "harn": 15,
        "harnPerPortion": 19,
        "purin": 6,
        "purinPerPortion": 8,
        "portionG": 125
    },
    {
        "key": 257,
        "cat": "Obst",
        "name": "Datteln, trocken",
        "kind": "",
        "harn": 15,
        "harnPerPortion": 4,
        "purin": 6,
        "purinPerPortion": 2,
        "portionG": 25
    },
    {
        "key": 258,
        "cat": "Obst",
        "name": "Erdbeeren",
        "kind": "",
        "harn": 25,
        "harnPerPortion": 31,
        "purin": 10,
        "purinPerPortion": 13,
        "portionG": 125
    },
    {
        "key": 259,
        "cat": "Obst",
        "name": "Feigen (Trockenobst)",
        "kind": "",
        "harn": 68,
        "harnPerPortion": 17,
        "purin": 28,
        "purinPerPortion": 7,
        "portionG": 25
    },
    {
        "key": 260,
        "cat": "Obst",
        "name": "Grapefruit",
        "kind": "",
        "harn": 15,
        "harnPerPortion": 19,
        "purin": 6,
        "purinPerPortion": 8,
        "portionG": 125
    },
    {
        "key": 261,
        "cat": "Obst",
        "name": "Heidelbeeren",
        "kind": "",
        "harn": 25,
        "harnPerPortion": 31,
        "purin": 10,
        "purinPerPortion": 13,
        "portionG": 125
    },
    {
        "key": 262,
        "cat": "Obst",
        "name": "Himbeeren",
        "kind": "",
        "harn": 20,
        "harnPerPortion": 25,
        "purin": 8,
        "purinPerPortion": 10,
        "portionG": 125
    },
    {
        "key": 263,
        "cat": "Obst",
        "name": "Honigmelone",
        "kind": "",
        "harn": 18,
        "harnPerPortion": 23,
        "purin": 8,
        "purinPerPortion": 10,
        "portionG": 125
    },
    {
        "key": 264,
        "cat": "Obst",
        "name": "Johannisbeeren",
        "kind": "",
        "harn": 15,
        "harnPerPortion": 19,
        "purin": 6,
        "purinPerPortion": 8,
        "portionG": 125
    },
    {
        "key": 265,
        "cat": "Obst",
        "name": "Kirschen, süß",
        "kind": "",
        "harn": 15,
        "harnPerPortion": 18,
        "purin": 6,
        "purinPerPortion": 8,
        "portionG": 120
    },
    {
        "key": 266,
        "cat": "Obst",
        "name": "Kiwi",
        "kind": "",
        "harn": 19,
        "harnPerPortion": 24,
        "purin": 8,
        "purinPerPortion": 10,
        "portionG": 125
    },
    {
        "key": 267,
        "cat": "Obst",
        "name": "Orangen",
        "kind": "",
        "harn": 20,
        "harnPerPortion": 30,
        "purin": 8,
        "purinPerPortion": 13,
        "portionG": 150
    },
    {
        "key": 268,
        "cat": "Obst",
        "name": "Pfirsich",
        "kind": "",
        "harn": 18,
        "harnPerPortion": 23,
        "purin": 8,
        "purinPerPortion": 10,
        "portionG": 125
    },
    {
        "key": 269,
        "cat": "Obst",
        "name": "Pflaumen (Trockenobst)",
        "kind": "",
        "harn": 111,
        "harnPerPortion": 28,
        "purin": 46,
        "purinPerPortion": 12,
        "portionG": 25
    },
    {
        "key": 270,
        "cat": "Obst",
        "name": "Preiselbeeren",
        "kind": "",
        "harn": 13,
        "harnPerPortion": 16,
        "purin": 5,
        "purinPerPortion": 7,
        "portionG": 125
    },
    {
        "key": 271,
        "cat": "Obst",
        "name": "Rhabarber",
        "kind": "",
        "harn": 5,
        "harnPerPortion": 6,
        "purin": 2,
        "purinPerPortion": 3,
        "portionG": 125
    },
    {
        "key": 272,
        "cat": "Obst",
        "name": "Rosinen (Trockenobst)",
        "kind": "",
        "harn": 107,
        "harnPerPortion": 27,
        "purin": 45,
        "purinPerPortion": 11,
        "portionG": 25
    },
    {
        "key": 273,
        "cat": "Obst",
        "name": "Stachelbeeren",
        "kind": "",
        "harn": 15,
        "harnPerPortion": 19,
        "purin": 6,
        "purinPerPortion": 8,
        "portionG": 125
    },
    {
        "key": 274,
        "cat": "Obst",
        "name": "Wassermelone",
        "kind": "",
        "harn": 20,
        "harnPerPortion": 25,
        "purin": 8,
        "purinPerPortion": 10,
        "portionG": 125
    },
    {
        "key": 275,
        "cat": "Obst",
        "name": "Weintrauben",
        "kind": "",
        "harn": 20,
        "harnPerPortion": 25,
        "purin": 8,
        "purinPerPortion": 10,
        "portionG": 125
    },
    {
        "key": 276,
        "cat": "Obst",
        "name": "Zwetschgen",
        "kind": "",
        "harn": 20,
        "harnPerPortion": 25,
        "purin": 8,
        "purinPerPortion": 10,
        "portionG": 125
    },
    {
        "key": 277,
        "cat": "Süßwaren",
        "name": "Honig",
        "kind": "",
        "harn": 0,
        "harnPerPortion": 0,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 20
    },
    {
        "key": 278,
        "cat": "Süßwaren",
        "name": "Konfitüre",
        "kind": "",
        "harn": 6,
        "harnPerPortion": 1,
        "purin": 3,
        "purinPerPortion": 0,
        "portionG": 20
    },
    {
        "key": 279,
        "cat": "Süßwaren",
        "name": "Marmelade",
        "kind": "",
        "harn": 6,
        "harnPerPortion": 1,
        "purin": 3,
        "purinPerPortion": 0,
        "portionG": 20
    },
    {
        "key": 280,
        "cat": "Süßwaren",
        "name": "Marzipan",
        "kind": "",
        "harn": 13,
        "harnPerPortion": 10,
        "purin": 5,
        "purinPerPortion": 4,
        "portionG": 75
    },
    {
        "key": 281,
        "cat": "Süßwaren",
        "name": "Nuss-Nougat-Creme",
        "kind": "",
        "harn": 12,
        "harnPerPortion": 2,
        "purin": 5,
        "purinPerPortion": 1,
        "portionG": 20
    },
    {
        "key": 282,
        "cat": "Süßwaren",
        "name": "Vanilleeiscreme",
        "kind": "",
        "harn": 1,
        "harnPerPortion": 1,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 100
    },
    {
        "key": 283,
        "cat": "Süßwaren",
        "name": "Vollmilchschokolade",
        "kind": "",
        "harn": 60,
        "harnPerPortion": 12,
        "purin": 25,
        "purinPerPortion": 5,
        "portionG": 20
    },
    {
        "key": 284,
        "cat": "Süßwaren",
        "name": "Zartbitterschokolade",
        "kind": "",
        "harn": 26,
        "harnPerPortion": 5,
        "purin": 11,
        "purinPerPortion": 2,
        "portionG": 20
    },
    {
        "key": 285,
        "cat": "Süßwaren",
        "name": "Zucker",
        "kind": "",
        "harn": 0,
        "harnPerPortion": 0,
        "purin": 0,
        "purinPerPortion": 0,
        "portionG": 5
    },
    {
        "key": 286,
        "cat": "Sonstige",
        "name": "Gelatine",
        "kind": "",
        "harn": 15,
        "harnPerPortion": 0,
        "purin": 6,
        "purinPerPortion": 0,
        "portionG": 1
    },
    {
        "key": 287,
        "cat": "Sonstige",
        "name": "Hefe",
        "kind": "",
        "harn": 680,
        "harnPerPortion": 34,
        "purin": 283,
        "purinPerPortion": 14,
        "portionG": 5
    },
    {
        "key": 288,
        "cat": "Sonstige",
        "name": "Ketchup",
        "kind": "",
        "harn": 78,
        "harnPerPortion": 16,
        "purin": 33,
        "purinPerPortion": 7,
        "portionG": 20
    },
    {
        "key": 289,
        "cat": "Sonstige",
        "name": "Meerrettich",
        "kind": "",
        "harn": 30,
        "harnPerPortion": 5,
        "purin": 13,
        "purinPerPortion": 2,
        "portionG": 15
    },
    {
        "key": 290,
        "cat": "Sonstige",
        "name": "Tomatenmark",
        "kind": "",
        "harn": 79,
        "harnPerPortion": 9,
        "purin": 33,
        "purinPerPortion": 4,
        "portionG": 10
    }
]